name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Clone paho.mqtt.c
      run: git clone https://github.com/eclipse-paho/paho.mqtt.c.git

    - name: Make paho.mqtt.c
      run: cd paho.mqtt.c && make install -j8

    - name: Install dependencies
      run: sudo apt-get install -y libsystemd-dev make build-essential

    - name: Build
      run: make